#!/usr/bin/env python3
"""Explain each difference class from diff_bundles.py using only cited sources from the pinned migration guide,
generated by the local llama.cpp model. Runs in the haystack-ai 3.1 env (uses its BM25 retriever + OpenAIChatGenerator).

  .venv-hs31/bin/python slice/regression/explain.py runtime/eval/regression/diff-hs231-hs31.json --out runtime/eval/regression/explain.json

Grounding rule enforced in the prompt and checked afterwards: every sentence must end with a citation [S1]..[Sn]
that points at one of the retrieved MIGRATION.md sections, or carry the marker NO SOURCE. Sentences that do neither are
counted as ungrounded. Nothing here is presented as correct until a person reviews it (see eval/feedback.yaml).
"""
import argparse, hashlib, json, os, re, sys, time
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from reports import pins_for_class, split_sections
from diff_bundles import diff_identity

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MIGRATION = os.path.join(ROOT, "corpus", "MIGRATION.md")
LLM_URL = os.environ.get("LLM_URL", "http://127.0.0.1:8081/v1")

CLASS_QUERY = {
    "ID_CHANGED_SAME_CONTENT": "Document.id auto-generated hash meta canonical JSON key-sorted changed",
    "SPLIT_CHANGED": "DocumentSplitter split behavior change chunks",
    "RANK_CHANGED": "InMemoryBM25Retriever ranking score change",
    "SCORE_CHANGED": "InMemoryBM25Retriever score scale_score change",
    "DOC_MISSING": "retriever top_k filters results missing documents",
    "DOC_EXTRA": "retriever top_k filters results extra documents",
    "PIPELINE_CONFIG_CHANGED": "Pipeline serialization to_dict from_dict changes",
    "RUNTIME_ERROR": "removed components import error replacement",
}


def split_markdown_sections(text):
    return split_sections(text, min_len=41)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("diff"); ap.add_argument("--out", required=True); ap.add_argument("--top-k", type=int, default=3)
    ap.add_argument("--feedback", default=None, help="reports file (default eval/feedback.yaml)")
    ap.add_argument("--sources-only", action="store_true", help="select sources and pins without calling the model")
    args = ap.parse_args()
    from haystack import Document
    from haystack.document_stores.in_memory import InMemoryDocumentStore
    from haystack.components.retrievers.in_memory import InMemoryBM25Retriever
    from haystack.components.generators.chat import OpenAIChatGenerator
    from haystack.dataclasses import ChatMessage
    from haystack.utils import Secret

    diff = json.load(open(args.diff))
    classes = sorted(set(diff["global"]) | {c for q in diff["queries"] for c in q["classes"] if c != "IDENTICAL"})
    store = InMemoryDocumentStore()
    store.write_documents([Document(content=b, meta={"source": "MIGRATION.md", "heading": t}) for t, b in split_markdown_sections(open(MIGRATION, encoding="utf-8").read())])
    retriever = InMemoryBM25Retriever(document_store=store, top_k=args.top_k)
    llm = OpenAIChatGenerator(api_base_url=LLM_URL, api_key=Secret.from_token("local"), model="qwen3-4b",
                              generation_kwargs={"temperature": 0.2, "max_tokens": 900}, timeout=900)

    def section_hash(text):
        return hashlib.sha1((text or "").encode("utf-8")).hexdigest()

    # recorded so a later reader can tell whether this explanation still belongs to a comparison and to these sources
    out = {"before": diff["before"], "after": diff["after"], "llm": {"url": LLM_URL, "model": "qwen3-4b"},
           "diff_identity": diff_identity(diff), "explanations": []}
    for cls in classes:
        example = next((q for q in diff["queries"] if cls in q["classes"]), None)
        detail = json.dumps((example or {}).get("details", [])[:2], ensure_ascii=False)
        sources = retriever.run(query=CLASS_QUERY.get(cls, cls))["documents"]
        # reports (wrong/missed on this class) pin the evidence they name as extra sources for this run
        all_sections = {t: b for t, b in split_markdown_sections(open(MIGRATION, encoding="utf-8").read())}
        pinned, unmatched = pins_for_class(cls, list(all_sections.keys()), feedback_path=args.feedback)
        have = {d.meta["heading"] for d in sources}
        pinned_tags = {}
        for pin in pinned:
            if pin["heading"] not in have:
                sources.append(Document(content=all_sections[pin["heading"]], meta={"source": "MIGRATION.md", "heading": pin["heading"], "pinned": True}, score=0.0))
                have.add(pin["heading"])
            else:  # already retrieved by BM25: still mark it so the screen shows the report was honored
                for d in sources:
                    if d.meta["heading"] == pin["heading"]:
                        d.meta["pinned"] = True
            pinned_tags[pin["heading"]] = f"S{[d.meta['heading'] for d in sources].index(pin['heading']) + 1}"
        src_block = "\n\n".join(f"[S{i}] ({d.meta['source']} — {d.meta['heading']}{' — added from a reviewer report' if d.meta.get('pinned') else ''})\n{d.content[:1800]}" for i, d in enumerate(sources, 1))
        notes = [f"- {p['report']['verdict']}: {p['report']['note']}" for p in pinned if p['report'].get('note')]
        if notes:
            src_block += "\n\nReviewer notes from earlier reports (fix these points, cite sources):\n" + "\n".join(notes)
        if args.sources_only:
            out["explanations"].append({"class": cls, "example_query": (example or {}).get("id"), "query_used": CLASS_QUERY.get(cls, cls),
                "sources": [{"tag": f"S{i}", "heading": d.meta["heading"], "score": round(float(d.score or 0), 3), "pinned": bool(d.meta.get("pinned"))} for i, d in enumerate(sources, 1)],
                "pinned": [{"tag": pinned_tags.get(p["heading"]), "heading": p["heading"], "report": p["report"]} for p in pinned],
                "source_hashes": {d.meta["heading"]: section_hash(d.content) for d in sources},
                "unmatched_reports": unmatched, "text": "", "sentences": 0, "cited": 0, "no_source": 0, "ungrounded": 0, "ungrounded_sentences": [],
                "truncated": False, "finish_reason": None, "latency_s": 0, "usage": {}, "tokens_per_s": None, "human_review": "sources-only (no model call)"})
            print(f"{cls}: sources {len(sources)} (pinned {len(pinned)}, unmatched reports {len(unmatched)}) [sources-only]")
            continue
        system = ("You explain differences observed when the same retrieval pipeline runs on haystack-ai "
                  f"{diff['before']['haystack']} and {diff['after']['haystack']}. Use ONLY the sources given. "
                  "Every sentence must end with a citation like [S1] to a source that supports it, or with the marker NO SOURCE. "
                  "Be concrete and short, at most 6 sentences: 1) what changed, 2) why, 3) what the developer should do. /no_think")
        user = (f"Observed difference class: {cls}\nExample detail from the diff: {detail}\n\nSources:\n{src_block}\n\n"
                "Explain and propose the fix. Cite every sentence.")
        t0 = time.time()
        rep = llm.run(messages=[ChatMessage.from_system(system), ChatMessage.from_user(user)])["replies"][0]
        dt = time.time() - t0
        text = re.sub(r"<think>.*?</think>", "", rep.text or "", flags=re.S).strip()
        sentences = [s.strip() for s in re.split(r"(?<=[.!?])\s+|\n+", text) if s.strip()]
        cited = [s for s in sentences if re.search(r"\[S\d+\]", s)]
        nosrc = [s for s in sentences if "NO SOURCE" in s]
        ungrounded = [s for s in sentences if s not in cited and s not in nosrc]
        finish = (rep.meta or {}).get("finish_reason")
        truncated = finish == "length" or (bool(sentences) and not re.search(r"[.!?]\s*(\[S\d+\])?\s*$", sentences[-1]))
        if truncated and sentences and sentences[-1] not in ungrounded:
            ungrounded.append(sentences[-1])  # a cut-off tail is not a grounded sentence even if it carries a citation
        usage = (rep.meta or {}).get("usage") or {}
        out["explanations"].append({
            "class": cls, "example_query": (example or {}).get("id"), "query_used": CLASS_QUERY.get(cls, cls),
            "sources": [{"tag": f"S{i}", "heading": d.meta["heading"], "score": round(float(d.score or 0), 3), "pinned": bool(d.meta.get("pinned"))} for i, d in enumerate(sources, 1)],
            "pinned": [{"tag": pinned_tags.get(p["heading"]), "heading": p["heading"], "report": p["report"]} for p in pinned],
            "source_hashes": {d.meta["heading"]: section_hash(d.content) for d in sources},
            "unmatched_reports": unmatched,
            "text": text, "sentences": len(sentences), "cited": len(cited), "no_source": len(nosrc), "ungrounded": len(ungrounded),
            "ungrounded_sentences": ungrounded[:5], "truncated": truncated, "finish_reason": finish, "latency_s": round(dt, 2), "usage": usage,
            "tokens_per_s": round(usage.get("completion_tokens", 0) / dt, 2) if dt and usage.get("completion_tokens") else None,
            "human_review": "pending"})
        print(f"{cls}: {len(sentences)} sentences, cited {len(cited)}, NO SOURCE {len(nosrc)}, ungrounded {len(ungrounded)}, {dt:.1f}s")
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    json.dump(out, open(args.out, "w"), indent=2, ensure_ascii=False)
    print("written", args.out)


if __name__ == "__main__":
    sys.exit(main())
